[global]
# Enable debug level logging or configure level directly
debug = false
log_level = "WARNING"

poll_interval = 5
reconnect_wait = 1

# The following can be overridden per player.
[options]
# Whether to show status for paused players.
show_paused = true
# Whether to show status for previously active and now stopped player.
show_stopped = false
# Available values are: "elapsed", "remaining" or "none".
show_time = "elapsed"
# Whether to ignore a player. Supposed to be overridden.
ignore = false

# You can override any of the [options] options
# for each player individually.
# The player name to use as the key
# is shown in your Discord Rich Presence (hover the icons).
[player.Spotify]
ignore = true
